name: C Inventory

on:
    push:
        branches: "main"
        tags:
            - 'v*'
    pull_request:
        branches: "main"

jobs:
    build:
        name: Test Code Validity
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                  - os: ubuntu-latest
                    artifact_name: InventorySystem_linux
                  - os: windows-latest
                    artifact_name: InventorySystem_Windows.exe

        runs-on: ${{ matrix.os }}

        steps:
            - name: Check repository code
              uses: actions/checkout@v4

            - name: Install tools and valgrind
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential valgrind

            - name: Set up Make for Win64
              if: matrix.os == 'windows-latest'
              run : |
                echo "Using built-in windows development tools"

            - name: Compile projects
              run: make all

            - name: Check for memory leaks
              if: matrix.os == 'ubuntu-latest'
              run: echo '0' | make memcheck

            - name: Rename executable for release
              shell: bash
              run: |
                if [ "{{ matrix.os }}" == "windows-latest" ]; then
                  mv bin/inventorysystem.exe ${{ matrix.artifact_name }} || echo "No exectuable (.exe) found, matching name"
                else
                  mv bin/inventorysystem ${{ matrix.artifact_name }} || echo "No binary file found, matching name"
                fi

            - name: Upload Artifacts for Release
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.artifact_name }}
                path: ${{ matrix.artifact_name }}

    release:
        name: Create Runnable App
        needs: build
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
            - name: Download all compiled binary
              uses: actions/download-artifact@v4
              with:
                path: ./artifacts
                merge-multiple: true
              
            - name: Create Automated Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                name: Release ${{ github.ref_name }}
                draft: false
                prerelease: false
                files: |
                  ./artifacts/InventorySystem_linux
                  ./artifacts/InventorySystem_Windows.exe
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}